apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grantory-controller
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - grantory.ansgar.tasler.net
    resources:
      - grantoryhosts
      - grantoryrequests
      - grantoryregisters
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - grantory.ansgar.tasler.net
    resources:
      - grantoryhosts/status
      - grantoryrequests/status
      - grantoryregisters/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
